services:
  # promtail:
  #   image: grafana/promtail:latest
  #   container_name: promtail
  #   volumes:
  #     - ./collectors/promtail/config/promtail.yaml:/etc/promtail/promtail.yaml        # Config file
  #     - ./logs:/var/log/services                                           # Bind-mounted log directory
  #     - ./collectors/promtail/config/positions.yaml:/tmp/positions.yaml              # Persisted positions
  #   command: -config.file=/etc/promtail/promtail.yaml

  logrotate:
    build:
      context: ./collectors/log_rotate
    container_name: logrotate
    volumes:
      - ./logs:/var/log/services
      # make sure linux line endings are used and not CRLF
      - ./collectors/log_rotate:/etc/logrotate.d
  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    container_name: logstash
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./collectors/logstash/pipeline:/usr/share/logstash/pipeline
      - ./logs:/var/log/services
    ports:
      - "9600:9600"
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disable security for local testing
    ports:
      - "9200:9200"  # Elasticsearch HTTP
      - "9300:9300"  # Elasticsearch Transport
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.4
    container_name: filebeat
    user: root
    volumes:
      # Filebeat config
      - ./collectors/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      # Access to logs
      - ./logs:/var/log/services
      # Filebeat registry (to track read positions)
      - filebeat_data:/usr/share/filebeat/data
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    command: >
      sh -c "chmod go-w /usr/share/filebeat/filebeat.yml && filebeat"
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.13.4
    container_name: metricbeat
    user: root
    volumes:
      - ./collectors/metricbeat/config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup
      - /proc:/hostfs/proc
      - /:/hostfs
    depends_on:
      - elasticsearch
    command: >
      sh -c "chmod go-w /usr/share/metricbeat/metricbeat.yml && metricbeat"

volumes:
  filebeat_data:
