server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push   # Safe to leave even if Loki isn't set up yet

scrape_configs:
  - job_name: container_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: container_logs
          __path__: /var/log/services/*/*.log
    relabel_configs:
      - source_labels: [__path__]
        regex: /var/log/services/(.+?)/.*
        target_label: service
